module.exports = {
  cid: "CID_028_Athena_Commando_F",
  eid: "EID_Floss",
  bid: "BID_004_BlackKnight",
  pickaxeId: "Pickaxe_Lockjaw",
  level: 999,
  bp: 69420,
  token: "TOKEN",
  prefix: "-",
  discordStatus: "%ClientUserDisplayName%'s account | %PartyMemberCount% / 16",
  discordStatusType: "WATCHING",
  discordUserStatus: "idle",
  customJoinMessage: "Hey %Member%!",
  fortniteStatus: "Hey",
  fortnitePlatform": "WIN",
  fortniteKairosID: "CID_028_Athena_Commando_F",
  acceptInvite: true,
  acceptFriend: true,
  ownerIDs: ["OWNER_ID"],
  ownerOnly: true
}
